### ISSUE TITLE
I cannot make it work

### ISSUE THREAD

**Issue by tibillys** [jrmdev/mitm_relay#1]
Sorry for posting this to issues but i cannot make it work... i have a windows client that does not support proxy.. I used another application to proxify the client and sent all the traffic to your script but after the first request i never get a response.

Your traffic flow diagram confused me . Do i need to instances of your script ?

Thank you

**Comment by jrmdev** [comment]
Hi,

You don't need two instances. The traffic flow diagram might be confusing, I'll update it to make it clearer. Regarding your setup, if you're running your windows client and mitm_relay on two different machines (or VMs), I'd recommend you drop your "proxify" app, and modify your hosts file. Check which server your client is connecting to (maybe by looking at the DNS lookups in wireshark), and then in the hosts file, point this address to your machine where mitm_relay listens. Make it listen on the same port as the actual server.

The second option could be to create iptables rules on your mitm_relay machine. Check out the readme, there's some examples.
