### ISSUE TITLE
param -r issue

### ISSUE THREAD

**Issue by fulamenge** [jrmdev/mitm_relay#14]
Now I want to exec the script and listen on my desktop, meanwhile let mobile device connect to it, all requests are sent by APP, but there are Http and non-Http requests in the whole process, so how should I write the param -r? Is my command right?
python mitm_relay.py -l 0.0.0.0 -p 127.0.0.1:8888 -r 4500:***.****.com:8082 -c server.pem -k server.key

**Comment by jrmdev** [comment]
You can't use wildcard in the destination server name. Use the complete name or IP address. Then force your app to connect to TCP port 4500 on your desktop. Otherwise your command is fine.

**Comment by fulamenge** [comment]
But i also have many HTTP/HTTPS traffic, if I redirect all traffic to a single tcp port they will not work as normal. How can I deal with it?

**Comment by jrmdev** [comment]
The best is not to redirect traffic for ports that you don't want to intercept.

The other option (probably the easiest if your app speaks to different ports on the same server), is to relay traffic for all ports that are used by your app by creating one relay per destination port (for clarity I recommend using the same port numbers for the relays you create as the destination port numbers used by the app). It doesn't matter if it's HTTP(S) or something else, it will still relay correctly. Just ignore the traffic for ports that you're not interested in.
