### ISSUE TITLE
How are you going to bind it?

### ISSUE THREAD

**Issue by archerhush** [jrmdev/mitm_relay#15]
First of all, looks like a nice/simple project.
Secondly, I'm trying to bind it like this:

python mitm_relay.py -l 127.0.0.1 -p 127.0.0.1:8081 -r port:164.132.238.228:port

it's an online website. I've found that IP source through wireshark. What do you mean with putting two ports (before and after the IP address you're targeting at?).
Thanks.

**Comment by jrmdev** [comment]
Hello and thank you for your comments.

The port number on the left is the port that will listen on your local machine, and that you should point your client to.
The port number on the right is the matching destination port on the destination server, that the traffic will be forwarded to after interception.
