### ISSUE TITLE
Burp Repeater support

### ISSUE THREAD

**Issue by gao-hui** [jrmdev/mitm_relay#24]
I use mitm_relay to relay SIP protocol. It works perfect.
But I want to send some packet myself, Repeater of burp is more convenient.
Is this possible to support Burp Repeater ?

**Comment by jrmdev** [comment]
This is impossible. Burp can only do HTTP, not any of the protocols you intercept through mitm_relay. Burp only does HTTP and can only talk with mitm_relay's internal web server, and is incapable of talking directly to your endpoint.

**Comment by gao-hui** [comment]
> This is impossible. Burp can only do HTTP, not any of the protocols you intercept through mitm_relay. It can only talk with mitm_relay's internal web server, and is incapable of talking directly to your endpoint.

Yes, Burp absolutely cannot talk directly to endpoint. 
I mean if it is possible to add something for mitm_relay to support Burp Repeater, where I can use my crafted SIP message? (maybe, Burp Repeater -> web_server -> ... -> SIP endpoint).
As in the description of intercept procedure in your README, ,we can use Burp Proxy to intercept and modify messages. (like, thick client -> listeners ->Burp Proxy -> web sever -> ... -> endpoint). 
Or, say it, like Burp Proxy procedure (intercept and modify messages, then send it to dummy web sever... then to endpoint through mitm_relay), is it possible to do similar thing using Burp  Repeater (send crafted messages directly to dummy web sever... then to endpoint through mitm_relay).
