### ISSUE TITLE
Forwarding to Burp/proxy does not happen with -p set

### ISSUE THREAD

**Issue by domi007** [jrmdev/mitm_relay#28]
Since the major update of 2022 the tool works great, however when setting a proxy with ```-p``` it does not actually forward traffic to the proxy, because the ```urlopen``` call is never told to use a proxy.
I was able to fix this by prefixing the call to ```mitm_relay.py``` with the environment variable ```HTTP_PROXY``` like this:

```HTTP_PROXY=127.0.0.1:8080 python3 mitm_relay -p 127.0.0.1:8080```

**Comment by jrmdev** [comment]
Fixed in 1b74741fbdd27b31d18e47741cab4c8b7d7baf15.

Thank you.
